version: '3.8'
services:
  app:
    build: .
    container_name: url_shortener_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: url_shortener_db
    environment:
      MYSQL_DATABASE: url_shortener_db
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
